### ISSUE TITLE
Panic when using converter, always when something with config, pls watch that

### ISSUE THREAD

**Issue by profileWhat** [singl3focus/hl7-converter#1]
Ошибка возникает когда в сообщении меньше полей чем указано в конфиге (меньше потому что пустые). Можно заполнить до конца символом разделения компонентов ( | )перед конвертацией сообщения 

panic: runtime error: index out of range [3] with length 1

goroutine 8 [running]:
github.com/singl3focus/hl7-converter.(*Converter).getFieldComponent(0x401199999999999a?, {0xc00050d210, 0xc000529a8c?, 0x6cab85?}, 0x0?, 0x0?)
        C:/Users/vromanov/go/pkg/mod/github.com/singl3focus/hl7-converter@v0.0.0-20240716153402-ba5924155553/converter.go:537 +0xfa
github.com/singl3focus/hl7-converter.(*Converter).setValueToField(0xc0004a5ec0, 0xc00051fe90?, 0xc000529a8a?, {0xc00050d400, 0x1f, 0x1f}, {0xc00050d210, 0x1e, 0x1e})
        C:/Users/vromanov/go/pkg/mod/github.com/singl3focus/hl7-converter@v0.0.0-20240716153402-ba5924155553/converter.go:429 +0x53d
github.com/singl3focus/hl7-converter.(*Converter).setValueToFieldWithOneLink(0xc0004a5ec0, {0xc000529a90, 0x5}, 0xc0004a5a80, {0xc00050d400, 0x1f, 0x1f})
        C:/Users/vromanov/go/pkg/mod/github.com/singl3focus/hl7-converter@v0.0.0-20240716153402-ba5924155553/converter.go:460 +0x192
github.com/singl3focus/hl7-converter.(*Converter).setFieldInOutputRow(0xc0004a5ec0, {0xc000529a90, 0x5}, 0xc0004a5a80, {0xc00050d400, 0x1f, 0x1f})
        C:/Users/vromanov/go/pkg/mod/github.com/singl3focus/hl7-converter@v0.0.0-20240716153402-ba5924155553/converter.go:349 +0x8b
github.com/singl3focus/hl7-converter.(*Converter).assembleOutputRowMsg(0xc0004a5ec0, {0x1085b98, 0x1})
        C:/Users/vromanov/go/pkg/mod/github.com/singl3focus/hl7-converter@v0.0.0-20240716153402-ba5924155553/converter.go:278 +0x389
github.com/singl3focus/hl7-converter.(*Converter).ConvertRow(0xc0004a5ec0, {0xc0002b0ac0, 0x31})
        C:/Users/vromanov/go/pkg/mod/github.com/singl3focus/hl7-converter@v0.0.0-20240716153402-ba5924155553/converter.go:240 +0x39e
github.com/singl3focus/hl7-converter.(*Converter).Convert(0xc0004a5ec0, {0xc0002e6800, 0xab, 0x800})
        C:/Users/vromanov/go/pkg/mod/github.com/singl3focus/hl7-converter@v0.0.0-20240716153402-ba5924155553/converter.go:90 +0x1c5
github.com/singl3focus/hl7-converter.ConvertWithConverter({0xc0000869c0?, 0x54?}, {0xc0001dc690, 0x12}, {0xc0001d8e06?, 0x0?}, {0xc0001d8dd6, 0x6}, {0xc0002e6800, 0xab, ...}, ...)
        C:/Users/vromanov/go/pkg/mod/github.com/singl3focus/hl7-converter@v0.0.0-20240716153402-ba5924155553/example.go:47 +0x357
 
Пример конфига
[models_config.json](https://github.com/user-attachments/files/16388895/models_config.json)

**Comment by singl3focus** [comment]
Thanks for your feedback. This has been fixed in the converter since version 1.0.4. 

Now you can add field 'options' with value '["autofill"]' to the Tag object. See it in the example config: https://github.com/singl3focus/hl7-converter/blob/fbe42af84e1f0ea1122d76b0c965f636285a31d1/config.json
